### ISSUE TITLE
problem with dataset

### ISSUE THREAD

**Issue by shouvik-paul** [takuya-ki/swarm-intelligence#2]
[wine.zip](https://github.com/takuya-ki/swarm-intelligence/files/3170504/wine.zip)

I am trying to use the values of dataset.
I am facing some problem with dataset. I am using your code and trying to use the particle position from the value of  dataset(Wine dataset(Wine.csv)).  Can you provide a demo code for using dataset?
Kindly help me to use this pso code with any kind of dataset (wine, iris dataset etc.)

**Comment by takuya-ki** [comment]
Thank you for your interests.
Please kindly tell me what the data in each column represent and also the purpose of optimization.
What are you trying to optimize?

**Comment by takuya-ki** [comment]
> [wine.zip](https://github.com/takuya-ki/swarm-intelligence/files/3170504/wine.zip)
> 
> I am trying to use the values of dataset. I am facing some problem with dataset. I am using your code and trying to use the particle position from the value of dataset(Wine dataset(Wine.csv)). Can you provide a demo code for using dataset? Kindly help me to use this pso code with any kind of dataset (wine, iris dataset etc.)

@shouvik-paul 
Thank you for your interests.
Please kindly tell me what the data in each column represent and also the purpose of optimization.
What are you trying to optimize?

**Comment by takuya-ki** [comment]
@shouvik-paul 
If you still have any problems on this topic please let me know by submitting another issue! Thanks!
